import path from 'node:path';
import { readJson, writeJson, firstSentence } from './lib.js';

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--in') args.in = argv[++i];
    else if (a === '--out') args.out = argv[++i];
    else if (a === '--kind') args.kind = argv[++i];
  }
  return args;
}

function kindLabel(kind) {
  const k = String(kind || 'daily').toLowerCase();
  if (k === 'weekly') return 'Weekly';
  if (k === 'monthly') return 'Monthly';
  return 'Daily';
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.in || !args.out) {
    console.error('Usage: node enrich_selected.js --in <selected.json> --out <enriched.json> [--kind daily|weekly|monthly]');
    process.exit(2);
  }

  const selected = await readJson(args.in);
  const kind = args.kind || selected.kind || 'daily';
  const date = selected.date || 'unknown';
  const range = selected.range;

  const papers = (selected.papers || []).map((p) => {
    const summary = (p.summary || firstSentence(p.abstract) || '').trim();
    return {
      ...p,
      summary
    };
  });

  const rangeText = range?.from && range?.to
    ? `${range.from} → ${range.to}`
    : date;

  const title = `Scholar Radar · ${date} · Motion + HOI`;
  const subtitle = `${kindLabel(kind)} · ${rangeText} · Top ${papers.length}`;
  const footer = 'Generated by OpenClaw scholar · links in the accompanying message.';

  const enriched = {
    ...selected,
    title,
    subtitle,
    footer,
    papers
  };

  await writeJson(args.out, enriched);

  console.log(JSON.stringify({ ok: true, kind, in: args.in, out: args.out, count: papers.length }, null, 2));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
