import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readJson, firstSentence, wrapText } from './lib.js';

const execFileP = promisify(execFile);

function esc(s) {
  return String(s)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function mkSvg({ width, height, fontFamily, date, papers }) {
  const margin = 48;
  const gutter = 28;
  const headerH = 150;
  const footerH = 40;

  const n = papers.length;
  const cols = n > 12 ? 2 : 1;
  const rows = Math.ceil(n / cols);

  const colW = (width - margin * 2 - gutter * (cols - 1)) / cols;
  const bodyH = height - margin - headerH - footerH;
  const rowH = Math.floor(bodyH / rows);

  const title = `Scholar Radar · ${date} · Motion + HOI`;

  let svg = '';
  svg += `<?xml version="1.0" encoding="UTF-8"?>\n`;
  svg += `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">`;
  svg += `<rect x="0" y="0" width="${width}" height="${height}" fill="#ffffff"/>`;

  // Header
  svg += `<text x="${margin}" y="${margin + 52}" font-family="${esc(fontFamily)}" font-size="44" font-weight="700" fill="#111">${esc(title)}</text>`;
  svg += `<text x="${margin}" y="${margin + 95}" font-family="${esc(fontFamily)}" font-size="24" fill="#444">Top ${n} · signals: watchlist + broad scan + trending</text>`;
  svg += `<line x1="${margin}" y1="${margin + headerH - 24}" x2="${width - margin}" y2="${margin + headerH - 24}" stroke="#e5e7eb" stroke-width="2"/>`;

  const startY = margin + headerH;

  for (let i = 0; i < n; i++) {
    const col = cols === 1 ? 0 : (i < rows ? 0 : 1);
    const row = cols === 1 ? i : (i < rows ? i : (i - rows));

    const x = margin + col * (colW + gutter);
    const y = startY + row * rowH;

    const p = papers[i];

    const cardPad = 16;
    svg += `<rect x="${x}" y="${y + 8}" width="${colW}" height="${rowH - 12}" rx="16" fill="#fafafa" stroke="#e5e7eb"/>`;

    const idx = String(i + 1).padStart(2, '0');
    const head = `${idx}  ${p.title}`;
    const idLine = `${p.arxivId}  ·  ${Array.isArray(p.tags) && p.tags.length ? p.tags.join(', ') : '—'}${p.signals?.github?.stars ? `  ·  ⭐ ${p.signals.github.stars}` : ''}${p.signals?.watchHit ? '  ·  WATCH' : ''}`;

    const titleLines = wrapText(head, cols === 1 ? 44 : 34).slice(0, 2);
    const summary = (p.summaryZh || p.summary || firstSentence(p.abstract) || '').trim();
    const summaryLines = wrapText(summary, cols === 1 ? 52 : 40).slice(0, cols === 1 ? 3 : 4);

    let ty = y + 8 + cardPad + 28;
    for (const line of titleLines) {
      svg += `<text x="${x + cardPad}" y="${ty}" font-family="${esc(fontFamily)}" font-size="24" font-weight="700" fill="#111">${esc(line)}</text>`;
      ty += 30;
    }

    svg += `<text x="${x + cardPad}" y="${ty + 6}" font-family="${esc(fontFamily)}" font-size="18" fill="#555">${esc(idLine)}</text>`;
    ty += 30;

    for (const line of summaryLines) {
      svg += `<text x="${x + cardPad}" y="${ty + 10}" font-family="${esc(fontFamily)}" font-size="20" fill="#222">${esc(line)}</text>`;
      ty += 26;
    }
  }

  // Footer
  svg += `<text x="${margin}" y="${height - margin/2}" font-family="${esc(fontFamily)}" font-size="16" fill="#666">Generated by OpenClaw scholar · arXiv links are included in the accompanying message.</text>`;

  svg += `</svg>`;
  return svg;
}

async function main() {
  const args = process.argv.slice(2);
  const inIdx = args.indexOf('--in');
  const outIdx = args.indexOf('--out');

  if (inIdx === -1 || outIdx === -1) {
    console.error('Usage: node render_poster.js --in <enriched.json> --out <poster.png>');
    process.exit(2);
  }

  const inPath = args[inIdx + 1];
  const outPath = args[outIdx + 1];

  const enriched = await readJson(inPath);
  const settingsPath = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', 'config', 'settings.json');
  const settings = await readJson(settingsPath);

  const width = settings.poster.width;
  const height = settings.poster.height;
  const fontFamily = settings.poster.fontFamily;
  const date = enriched.date || 'unknown';
  const papers = enriched.papers || [];

  const svg = mkSvg({ width, height, fontFamily, date, papers });
  const tmpSvg = outPath.replace(/\.png$/i, '.svg');

  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(tmpSvg, svg, 'utf-8');

  // Rasterize SVG to PNG
  await execFileP('convert', ['-density', '200', tmpSvg, outPath]);

  console.log(JSON.stringify({ ok: true, outPath, svgPath: tmpSvg, count: papers.length }, null, 2));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
